name: Deploy Project to Staging

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and build
        run: npm install && npm run build

      - name: Deploy to Deployment Repo
        uses: actions/checkout@v3
        with:
          repository: Koafaith/codefest-deployment
          path: codefest-deployment
          token: ${{ secrets.DEPLOYMENT_REPO_TOKEN }}

      - name: Copy build files
        run: cp -r dist/* codefest-deployment/public/welcome/

      - name: Commit and push changes
        run: |
          cd codefest-deployment
          git config --local user.email "tanvitsao@koafaith.com"
          git config --local user.name "TanviTsao"
          git add .
          git commit -m "Update welcome page build" || true
          git push
